# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provider 'virtualbox' do |v|
        v.name = 'cert-ninja'
        v.gui = false
        v.memory = 4096 
        v.cpus = 4
    end

    config.vm.box = 'generic/ubuntu2004'
    config.vm.box_version = "3.1.16"

    config.vm.define 'ubuntu20.04' do |ubuntu|
        ubuntu.vm.hostname = 'ubuntu20.04'
    end

    if Vagrant.has_plugin?('vagrant-vbguest') then
        config.vbguest.auto_update = true 
    end

    config.vm.provision:shell, inline: <<-SHELL
        step=1
        step() {
            echo "Step $step $1"
            step=$((step+1))
        }

        resolve_dns() {
            step "===== Create symlink to /run/systemd/resolve/resolv.conf ====="
            sudo rm /etc/resolv.conf
            sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
        }

        set_timezone() {
            step "===== Setting timezone ====="
            sudo timedatectl set-timezone America/Mountain
        }

        install_docker() {
            step "===== Installing docker ====="
            sudo apt update
            sudo apt -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            if [ $? -ne 0 ]; then
                sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            fi
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt update
            sudo apt install -y docker-ce docker-ce-cli containerd.io
            sudo groupadd docker
            sudo gpasswd -a $USER docker
            sudo chmod 777 /var/run/docker.sock
            # Add vagrant to docker group
            sudo groupadd docker
            sudo gpasswd -a vagrant docker
            # Setup docker daemon host
            # Read more about docker daemon https://docs.docker.com/engine/reference/commandline/dockerd/
            sed -i 's/ExecStart=.*/ExecStart=\/usr\/bin\/dockerd -H unix:\/\/\/var\/run\/docker.sock -H tcp:\/\/192.168.121.210/g' /lib/systemd/system/docker.service
            sudo systemctl daemon-reload
            sudo systemctl restart docker
        }

        install_openssh() {
            step "===== Installing openssh ====="
            sudo apt update
            sudo apt -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            sudo apt install -y openssh-server
            sudo systemctl enable ssh
        }

        setup_root_login() {
            step "===== Permit root login ====="
            sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
            sudo systemctl restart ssh
            sudo echo "root:rootroot" | chpasswd
        }

        setup_welcome_msg() {
            step "===== Setup welcome message ====="
            sudo apt -y install cowsay
            sudo echo -e "\necho \"Welcome to Vagrant Ubuntu Server 18.04\" | cowsay\n" >> /home/vagrant/.bashrc
            sudo ln -s /usr/games/cowsay /usr/local/bin/cowsay
        }

        install_tools() {
            step "===== Install tools ====="
            sudo apt install -y python-pip
        }

        main() {
            resolve_dns
            set_timezone
            install_openssh
            setup_root_login
            setup_welcome_msg
            install_tools
        }

    SHELL
end